
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 21 17:06:07 CLT 2015
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java_cup.parser;
import java.io.*;
import java.util.*;
import AbstractSyntaxTree.*;
import Symbols.Token.*;
import scanner.Scanner;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Nov 21 17:06:07 CLT 2015
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\106\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\006\005\000\002\006\010\000\002\005\003\000" +
    "\002\005\003\000\002\007\010\000\002\011\003\000\002" +
    "\011\003\000\002\010\005\000\002\010\003\000\002\012" +
    "\004\000\002\012\006\000\002\023\006\000\002\020\004" +
    "\000\002\020\002\000\002\021\004\000\002\021\002\000" +
    "\002\022\003\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\033\004\000\002\033" +
    "\003\000\002\013\007\000\002\013\011\000\002\014\003" +
    "\000\002\014\003\000\002\015\007\000\002\017\013\000" +
    "\002\016\004\000\002\016\005\000\002\031\005\000\002" +
    "\031\003\000\002\030\003\000\002\030\006\000\002\036" +
    "\005\000\002\036\003\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\035\005\000\002\035\003\000\002" +
    "\025\003\000\002\025\003\000\002\034\005\000\002\034" +
    "\003\000\002\026\003\000\002\026\003\000\002\037\005" +
    "\000\002\037\003\000\002\027\003\000\002\027\003\000" +
    "\002\032\005\000\002\032\003\000\002\032\003\000\002" +
    "\032\003\000\002\040\006\000\002\041\003\000\002\041" +
    "\002\000\002\042\005\000\002\042\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\006\033\013\037\010\001\002\000\004\002" +
    "\170\001\002\000\010\002\ufffc\033\ufffc\037\ufffc\001\002" +
    "\000\010\002\ufffd\033\ufffd\037\ufffd\001\002\000\010\002" +
    "\000\033\013\037\010\001\002\000\004\040\ufff8\001\002" +
    "\000\004\040\014\001\002\000\010\002\ufffe\033\ufffe\037" +
    "\ufffe\001\002\000\004\040\ufff9\001\002\000\010\023\017" +
    "\025\016\027\015\001\002\000\034\002\ufffb\021\ufffb\022" +
    "\ufffb\025\ufffb\027\ufffb\031\ufffb\033\ufffb\034\ufffb\035\ufffb" +
    "\036\ufffb\037\ufffb\040\ufffb\041\ufffb\001\002\000\006\033" +
    "\013\037\024\001\002\000\004\041\020\001\002\000\004" +
    "\024\021\001\002\000\004\027\022\001\002\000\034\002" +
    "\ufffa\021\ufffa\022\ufffa\025\ufffa\027\ufffa\031\ufffa\033\ufffa" +
    "\034\ufffa\035\ufffa\036\ufffa\037\ufffa\040\ufffa\041\ufffa\001" +
    "\002\000\006\026\ufff6\030\165\001\002\000\006\026\ufff5" +
    "\040\ufff8\001\002\000\004\040\162\001\002\000\004\026" +
    "\030\001\002\000\006\026\ufff3\030\ufff3\001\002\000\004" +
    "\021\031\001\002\000\032\021\uffee\022\uffee\025\uffee\027" +
    "\uffee\031\uffee\033\uffee\034\uffee\035\uffee\036\uffee\037\uffee" +
    "\040\uffee\041\uffee\001\002\000\010\002\ufff7\033\ufff7\037" +
    "\ufff7\001\002\000\032\021\uffec\022\uffec\025\uffec\027\uffec" +
    "\031\uffec\033\013\034\uffec\035\uffec\036\uffec\037\010\040" +
    "\uffec\041\uffec\001\002\000\026\021\031\022\065\025\056" +
    "\027\041\031\047\034\044\035\043\036\066\040\050\041" +
    "\051\001\002\000\032\021\uffef\022\uffef\025\uffef\027\uffef" +
    "\031\uffef\033\uffef\034\uffef\035\uffef\036\uffef\037\uffef\040" +
    "\uffef\041\uffef\001\002\000\004\040\037\001\002\000\006" +
    "\023\017\027\015\001\002\000\030\021\uffe2\022\uffe2\025" +
    "\uffe2\027\uffe2\031\uffe2\032\uffe2\034\uffe2\035\uffe2\036\uffe2" +
    "\040\uffe2\041\uffe2\001\002\000\030\021\uffe5\022\uffe5\025" +
    "\uffe5\027\uffe5\031\uffe5\032\uffe5\034\uffe5\035\uffe5\036\uffe5" +
    "\040\uffe5\041\uffe5\001\002\000\026\021\uffed\022\uffed\025" +
    "\uffed\027\uffed\031\uffed\034\uffed\035\uffed\036\uffed\040\uffed" +
    "\041\uffed\001\002\000\004\025\156\001\002\000\012\025" +
    "\056\027\154\040\050\041\051\001\002\000\030\021\uffea" +
    "\022\uffea\025\uffea\027\uffea\031\uffea\032\uffea\034\uffea\035" +
    "\uffea\036\uffea\040\uffea\041\uffea\001\002\000\042\005\uffc7" +
    "\006\uffc7\007\uffc7\010\uffc7\011\uffc7\012\uffc7\013\uffc7\014" +
    "\uffc7\015\uffc7\016\uffc7\017\uffc7\020\uffc7\024\uffc7\026\uffc7" +
    "\027\uffc7\030\uffc7\001\002\000\004\025\145\001\002\000" +
    "\050\004\uffda\005\uffda\006\uffda\007\uffda\010\uffda\011\uffda" +
    "\012\uffda\013\uffda\014\uffda\015\uffda\016\uffda\017\uffda\020" +
    "\uffda\023\134\024\uffda\025\133\026\uffda\027\uffda\030\uffda" +
    "\001\002\000\042\005\uffc1\006\uffc1\007\uffc1\010\uffc1\011" +
    "\uffc1\012\uffc1\013\uffc1\014\uffc1\015\uffc1\016\uffc1\017\uffc1" +
    "\020\uffc1\024\uffc1\026\uffc1\027\uffc1\030\uffc1\001\002\000" +
    "\004\027\132\001\002\000\030\021\uffe7\022\uffe7\025\uffe7" +
    "\027\uffe7\031\uffe7\032\uffe7\034\uffe7\035\uffe7\036\uffe7\040" +
    "\uffe7\041\uffe7\001\002\000\042\005\111\006\110\007\uffcb" +
    "\010\uffcb\011\uffcb\012\uffcb\013\uffcb\014\uffcb\015\uffcb\016" +
    "\uffcb\017\uffcb\020\uffcb\024\uffcb\026\uffcb\027\uffcb\030\uffcb" +
    "\001\002\000\032\007\116\011\124\013\120\014\126\015" +
    "\127\016\121\017\125\020\117\024\uffd7\026\uffd7\027\uffd7" +
    "\030\uffd7\001\002\000\010\025\056\040\050\041\051\001" +
    "\002\000\036\007\uffcf\010\103\011\uffcf\012\105\013\uffcf" +
    "\014\uffcf\015\uffcf\016\uffcf\017\uffcf\020\uffcf\024\uffcf\026" +
    "\uffcf\027\uffcf\030\uffcf\001\002\000\012\024\uffdb\026\uffdb" +
    "\027\uffdb\030\uffdb\001\002\000\030\021\uffeb\022\uffeb\025" +
    "\uffeb\027\uffeb\031\uffeb\032\uffeb\034\uffeb\035\uffeb\036\uffeb" +
    "\040\uffeb\041\uffeb\001\002\000\030\021\uffe9\022\uffe9\025" +
    "\uffe9\027\uffe9\031\uffe9\032\uffe9\034\uffe9\035\uffe9\036\uffe9" +
    "\040\uffe9\041\uffe9\001\002\000\030\021\uffe8\022\uffe8\025" +
    "\uffe8\027\uffe8\031\uffe8\032\uffe8\034\uffe8\035\uffe8\036\uffe8" +
    "\040\uffe8\041\uffe8\001\002\000\030\021\uffe1\022\uffe1\025" +
    "\uffe1\027\uffe1\031\uffe1\032\uffe1\034\uffe1\035\uffe1\036\uffe1" +
    "\040\uffe1\041\uffe1\001\002\000\036\002\ufff0\021\ufff0\022" +
    "\ufff0\025\ufff0\027\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0" +
    "\035\ufff0\036\ufff0\037\ufff0\040\ufff0\041\ufff0\001\002\000" +
    "\004\025\073\001\002\000\042\005\uffc2\006\uffc2\007\uffc2" +
    "\010\uffc2\011\uffc2\012\uffc2\013\uffc2\014\uffc2\015\uffc2\016" +
    "\uffc2\017\uffc2\020\uffc2\024\uffc2\026\uffc2\027\uffc2\030\uffc2" +
    "\001\002\000\044\004\071\005\uffc3\006\uffc3\007\uffc3\010" +
    "\uffc3\011\uffc3\012\uffc3\013\uffc3\014\uffc3\015\uffc3\016\uffc3" +
    "\017\uffc3\020\uffc3\024\uffc3\026\uffc3\027\uffc3\030\uffc3\001" +
    "\002\000\010\025\056\040\050\041\051\001\002\000\012" +
    "\024\uffdc\026\uffdc\027\uffdc\030\uffdc\001\002\000\010\025" +
    "\056\040\050\041\051\001\002\000\004\030\075\001\002" +
    "\000\010\025\056\040\050\041\051\001\002\000\004\030" +
    "\077\001\002\000\010\025\056\040\050\041\051\001\002" +
    "\000\004\026\101\001\002\000\024\021\031\025\056\027" +
    "\041\031\047\034\044\035\043\036\066\040\050\041\051" +
    "\001\002\000\030\021\uffdf\022\uffdf\025\uffdf\027\uffdf\031" +
    "\uffdf\032\uffdf\034\uffdf\035\uffdf\036\uffdf\040\uffdf\041\uffdf" +
    "\001\002\000\010\025\uffca\040\uffca\041\uffca\001\002\000" +
    "\010\025\056\040\050\041\051\001\002\000\010\025\uffc9" +
    "\040\uffc9\041\uffc9\001\002\000\042\005\uffc3\006\uffc3\007" +
    "\uffc3\010\uffc3\011\uffc3\012\uffc3\013\uffc3\014\uffc3\015\uffc3" +
    "\016\uffc3\017\uffc3\020\uffc3\024\uffc3\026\uffc3\027\uffc3\030" +
    "\uffc3\001\002\000\042\005\111\006\110\007\uffcc\010\uffcc" +
    "\011\uffcc\012\uffcc\013\uffcc\014\uffcc\015\uffcc\016\uffcc\017" +
    "\uffcc\020\uffcc\024\uffcc\026\uffcc\027\uffcc\030\uffcc\001\002" +
    "\000\010\025\uffc5\040\uffc5\041\uffc5\001\002\000\010\025" +
    "\uffc6\040\uffc6\041\uffc6\001\002\000\010\025\056\040\050" +
    "\041\051\001\002\000\042\005\uffc8\006\uffc8\007\uffc8\010" +
    "\uffc8\011\uffc8\012\uffc8\013\uffc8\014\uffc8\015\uffc8\016\uffc8" +
    "\017\uffc8\020\uffc8\024\uffc8\026\uffc8\027\uffc8\030\uffc8\001" +
    "\002\000\004\026\115\001\002\000\042\005\uffc4\006\uffc4" +
    "\007\uffc4\010\uffc4\011\uffc4\012\uffc4\013\uffc4\014\uffc4\015" +
    "\uffc4\016\uffc4\017\uffc4\020\uffc4\024\uffc4\026\uffc4\027\uffc4" +
    "\030\uffc4\001\002\000\010\025\uffce\040\uffce\041\uffce\001" +
    "\002\000\010\025\uffd1\040\uffd1\041\uffd1\001\002\000\010" +
    "\025\uffd2\040\uffd2\041\uffd2\001\002\000\010\025\uffd4\040" +
    "\uffd4\041\uffd4\001\002\000\010\025\056\040\050\041\051" +
    "\001\002\000\010\025\056\040\050\041\051\001\002\000" +
    "\010\025\uffcd\040\uffcd\041\uffcd\001\002\000\010\025\uffd3" +
    "\040\uffd3\041\uffd3\001\002\000\010\025\uffd5\040\uffd5\041" +
    "\uffd5\001\002\000\010\025\uffd6\040\uffd6\041\uffd6\001\002" +
    "\000\036\007\uffd0\010\103\011\uffd0\012\105\013\uffd0\014" +
    "\uffd0\015\uffd0\016\uffd0\017\uffd0\020\uffd0\024\uffd0\026\uffd0" +
    "\027\uffd0\030\uffd0\001\002\000\016\007\116\011\124\024" +
    "\uffd8\026\uffd8\027\uffd8\030\uffd8\001\002\000\030\021\uffe6" +
    "\022\uffe6\025\uffe6\027\uffe6\031\uffe6\032\uffe6\034\uffe6\035" +
    "\uffe6\036\uffe6\040\uffe6\041\uffe6\001\002\000\012\025\056" +
    "\026\uffbe\040\050\041\051\001\002\000\010\025\056\040" +
    "\050\041\051\001\002\000\004\024\136\001\002\000\044" +
    "\004\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012" +
    "\uffd9\013\uffd9\014\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9" +
    "\024\uffd9\026\uffd9\027\uffd9\030\uffd9\001\002\000\006\026" +
    "\uffbf\030\143\001\002\000\006\026\uffbc\030\uffbc\001\002" +
    "\000\004\026\142\001\002\000\042\005\uffc0\006\uffc0\007" +
    "\uffc0\010\uffc0\011\uffc0\012\uffc0\013\uffc0\014\uffc0\015\uffc0" +
    "\016\uffc0\017\uffc0\020\uffc0\024\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\001\002\000\010\025\056\040\050\041\051\001\002" +
    "\000\006\026\uffbd\030\uffbd\001\002\000\010\025\056\040" +
    "\050\041\051\001\002\000\004\026\147\001\002\000\024" +
    "\021\031\025\056\027\041\031\047\034\044\035\043\036" +
    "\066\040\050\041\051\001\002\000\030\021\uffe4\022\uffe4" +
    "\025\uffe4\027\uffe4\031\uffe4\032\151\034\uffe4\035\uffe4\036" +
    "\uffe4\040\uffe4\041\uffe4\001\002\000\024\021\031\025\056" +
    "\027\041\031\047\034\044\035\043\036\066\040\050\041" +
    "\051\001\002\000\030\021\uffe3\022\uffe3\025\uffe3\027\uffe3" +
    "\031\uffe3\032\uffe3\034\uffe3\035\uffe3\036\uffe3\040\uffe3\041" +
    "\uffe3\001\002\000\004\027\155\001\002\000\030\021\uffde" +
    "\022\uffde\025\uffde\027\uffde\031\uffde\032\uffde\034\uffde\035" +
    "\uffde\036\uffde\040\uffde\041\uffde\001\002\000\030\021\uffdd" +
    "\022\uffdd\025\uffdd\027\uffdd\031\uffdd\032\uffdd\034\uffdd\035" +
    "\uffdd\036\uffdd\040\uffdd\041\uffdd\001\002\000\010\025\056" +
    "\040\050\041\051\001\002\000\004\026\160\001\002\000" +
    "\024\021\031\025\056\027\041\031\047\034\044\035\043" +
    "\036\066\040\050\041\051\001\002\000\030\021\uffe0\022" +
    "\uffe0\025\uffe0\027\uffe0\031\uffe0\032\uffe0\034\uffe0\035\uffe0" +
    "\036\uffe0\040\uffe0\041\uffe0\001\002\000\010\023\163\026" +
    "\ufff2\030\ufff2\001\002\000\004\024\164\001\002\000\006" +
    "\026\ufff1\030\ufff1\001\002\000\006\033\013\037\010\001" +
    "\002\000\006\026\ufff4\030\ufff4\001\002\000\010\002\uffff" +
    "\033\uffff\037\uffff\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\016\002\003\003\006\004\011\005\010\006" +
    "\005\007\004\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\166\005\010\006\005\007" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\005\024\010\022\011\025\012\026\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\023" +
    "\031\001\001\000\004\020\032\001\001\000\002\001\001" +
    "\000\010\005\035\006\034\021\033\001\001\000\042\013" +
    "\061\014\062\015\037\016\052\017\063\022\041\023\044" +
    "\030\067\031\051\032\045\033\060\034\056\035\054\036" +
    "\057\037\053\040\066\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\030\067" +
    "\031\152\032\045\034\056\035\054\036\057\037\053\040" +
    "\066\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\027\111\001\001\000\006" +
    "\024\121\025\122\001\001\000\022\030\067\031\113\032" +
    "\045\034\056\035\054\036\057\037\053\040\066\001\001" +
    "\000\004\026\103\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\030\067\031\071\032\045\034\056" +
    "\035\054\036\057\037\053\040\066\001\001\000\002\001" +
    "\001\000\022\030\067\031\073\032\045\034\056\035\054" +
    "\036\057\037\053\040\066\001\001\000\002\001\001\000" +
    "\022\030\067\031\075\032\045\034\056\035\054\036\057" +
    "\037\053\040\066\001\001\000\002\001\001\000\022\030" +
    "\067\031\077\032\045\034\056\035\054\036\057\037\053" +
    "\040\066\001\001\000\002\001\001\000\042\013\061\014" +
    "\062\015\037\016\052\017\063\022\101\023\044\030\067" +
    "\031\051\032\045\033\060\034\056\035\054\036\057\037" +
    "\053\040\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\030\105\032\045\037\106\040\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\027\111\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\030\105\032" +
    "\112\040\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\030\105\032\045" +
    "\034\056\035\130\037\053\040\066\001\001\000\014\030" +
    "\105\032\045\034\127\037\053\040\066\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\026\103\001\001\000\004\025\122\001\001" +
    "\000\002\001\001\000\026\030\067\031\137\032\045\034" +
    "\056\035\054\036\057\037\053\040\066\041\140\042\136" +
    "\001\001\000\022\030\067\031\134\032\045\034\056\035" +
    "\054\036\057\037\053\040\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\030\067\031\143" +
    "\032\045\034\056\035\054\036\057\037\053\040\066\001" +
    "\001\000\002\001\001\000\022\030\067\031\145\032\045" +
    "\034\056\035\054\036\057\037\053\040\066\001\001\000" +
    "\002\001\001\000\042\013\061\014\062\015\037\016\052" +
    "\017\063\022\147\023\044\030\067\031\051\032\045\033" +
    "\060\034\056\035\054\036\057\037\053\040\066\001\001" +
    "\000\002\001\001\000\042\013\061\014\062\015\037\016" +
    "\052\017\063\022\151\023\044\030\067\031\051\032\045" +
    "\033\060\034\056\035\054\036\057\037\053\040\066\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\030\067\031\156\032\045\034" +
    "\056\035\054\036\057\037\053\040\066\001\001\000\002" +
    "\001\001\000\042\013\061\014\062\015\037\016\052\017" +
    "\063\022\160\023\044\030\067\031\051\032\045\033\060" +
    "\034\056\035\054\036\057\037\053\040\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\005\024\012\165\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public NodeTree root = null; /* nodo raiz del arbol sintactico abstracto */
    public String cadenaProduccion = " "; /* contiene la cadena de producciones */

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    /* Metodo encargado de desplegar mensaje de error con mayor informacion */
    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : "+message + " -> Parser");
        System.err.println(m);
    }

    public void syntax_error(Symbol s){
        System.out.println("Compilador a detectado un error sintáctico en la línea " + s.left + " y columna " + s.right + " -> " + s.value); 
    }

    /* Metodo encargado de iniciar el arbol sintactico abstracto */
    public void setAbstractSyntaxTree(NodeTree n){
        this.root = n;
    }

    /* Metodo encargado de obtener el arbol sintactico abstracto */
    public NodeTree getAbstractSyntaxTree() throws Exception {
        if(root == null){
            this.parse();
        }
        return this.root;
    }

    public static void main(String [] args){
        try{
            Parser p = new Parser(new Scanner( new FileReader(args[0])));
            Object result = p.parse().value;
        }
        catch(Exception e){
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // arg_list ::= expression 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "arg_list ::= expression \n"+this.parser.cadenaProduccion;
                                NodeCall nc = new NodeCall();
                                nc.listaNodos.add(e);
                                RESULT = nc;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // arg_list ::= arg_list COMMA expression 
            {
              NodeTree RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int alright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree al = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "arg_list ::= arg_list COMMA expression \n"+this.parser.cadenaProduccion;
                                if(e != null){
                                    NodeCall nc = new NodeCall();
                                    nc = (NodeCall)al;
                                    nc.listaNodos.add(e);
                                }
                                RESULT = al;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // args ::= 
            {
              NodeTree RESULT =null;
		
                                this.parser.cadenaProduccion = "args ::= EMPTY \n"+this.parser.cadenaProduccion;
                                NodeCall nc = new NodeCall();
                                RESULT = nc;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // args ::= arg_list 
            {
              NodeTree RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int alright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree al = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "args ::= arg_list \n"+this.parser.cadenaProduccion;
                                RESULT = al;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // call ::= ID LCIRCLEB args RCIRCLEB 
            {
              NodeTree RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int arleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int arright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeTree ar = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "call ::= ID:id LCIRCLEB args RCIRCLEB \n"+this.parser.cadenaProduccion;
                                NodeCall nc = new NodeCall();
                                nc.identificador = id;
                                nc.listaNodos.add(ar);
                                RESULT = nc;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("call",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // exp ::= NUM 
            {
              NodeTree RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "exp ::= NUM \n"+this.parser.cadenaProduccion;
                                NodeVar nv = new NodeVar();
                                nv.tipo = "numero";
                                nv.valorNumero = num;
                                nv.numero = num;
                                RESULT = nv;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // exp ::= call 
            {
              NodeTree RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree c = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "exp ::= call \n"+this.parser.cadenaProduccion;
                                RESULT = c;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // exp ::= var 
            {
              NodeTree RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree v = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "exp ::= var \n"+this.parser.cadenaProduccion;
                                RESULT = v;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= LCIRCLEB expression RCIRCLEB 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "exp ::= LCIRCLEB expression RCIRCLEB \n"+this.parser.cadenaProduccion;
                                RESULT = e;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // powop ::= EXPO2 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "powop ::= EXPO2 \n"+this.parser.cadenaProduccion;
                                RESULT = sym.EXPO2;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("powop",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // powop ::= EXPO1 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "powop ::= EXPO1 \n"+this.parser.cadenaProduccion;
                                RESULT = sym.EXPO1;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("powop",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= exp 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "factor ::= exp \n"+this.parser.cadenaProduccion;
                                RESULT = e;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= factor powop exp 
            {
              NodeTree RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree f = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "factor ::= factor powop exp \n"+this.parser.cadenaProduccion;
                                NodeExpression ne = new NodeExpression();
                                ne.operador = p;
                                ne.operando1 = f;
                                ne.operando2 = e;
                                RESULT = ne;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // mulop ::= DIV 
            {
              Integer RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "mulop ::= DIV \n"+this.parser.cadenaProduccion;
                                RESULT = sym.DIV;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mulop",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // mulop ::= MULT 
            {
              Integer RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "mulop ::= MULT \n"+this.parser.cadenaProduccion;
                                RESULT = sym.MULT;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mulop",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // term ::= factor 
            {
              NodeTree RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree f = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "term ::= factor \n"+this.parser.cadenaProduccion;
                                RESULT = f;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // term ::= term mulop factor 
            {
              NodeTree RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree t = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer m = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree f = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "term ::= term mulop factor \n"+this.parser.cadenaProduccion;
                                NodeExpression ne = new NodeExpression();
                                ne.operador = m;
                                ne.operando1 = t;
                                ne.operando2 = f;
                                RESULT = ne;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // addop ::= RESTA 
            {
              Integer RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "addop ::= RESTA \n"+this.parser.cadenaProduccion;
                                RESULT = sym.RESTA;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("addop",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // addop ::= SUMA 
            {
              Integer RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "addop ::= SUMA \n"+this.parser.cadenaProduccion;
                                RESULT = sym.SUMA;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("addop",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // additive_expression ::= term 
            {
              NodeTree RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree t = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "additive_expression ::= term \n"+this.parser.cadenaProduccion;
                                RESULT = t;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("additive_expression",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // additive_expression ::= additive_expression addop term 
            {
              NodeTree RESULT =null;
		int aeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree ae = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer a = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree t = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "additive_expression ::= additive_expression addop term \n"+this.parser.cadenaProduccion;
                                NodeExpression ne = new NodeExpression();
                                ne.operador = a;
                                ne.operando1 = ae;
                                ne.operando2 = t;
                                RESULT = ne;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("additive_expression",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // relop ::= NEQ 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= NEQ \n"+this.parser.cadenaProduccion;
                                RESULT = sym.NEQ;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // relop ::= EQ 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= EQ \n"+this.parser.cadenaProduccion;
                                RESULT = sym.EQ;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // relop ::= GEQ 
            {
              Integer RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int gright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object g = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= GEQ \n"+this.parser.cadenaProduccion;
                                RESULT = sym.GEQ;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // relop ::= GT 
            {
              Integer RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int gright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object g = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= GT \n"+this.parser.cadenaProduccion;
                                RESULT = sym.GT;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // relop ::= LT 
            {
              Integer RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= LT \n"+this.parser.cadenaProduccion;
                                RESULT = sym.LT;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // relop ::= LEQ 
            {
              Integer RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "relop ::= LEQ \n"+this.parser.cadenaProduccion;
                                RESULT = sym.LEQ;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // simple_expression ::= additive_expression 
            {
              NodeTree RESULT =null;
		int aeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree ae = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "simple_expression ::= additive_expression \n"+this.parser.cadenaProduccion;
                                RESULT = ae;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // simple_expression ::= additive_expression relop additive_expression 
            {
              NodeTree RESULT =null;
		int ae1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ae1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree ae1 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer r = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ae2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int ae2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree ae2 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "simple_expression ::= additive_expression relop aditive_expression \n"+this.parser.cadenaProduccion;
                                NodeExpression ne = new NodeExpression();
                                ne.operador = r;
                                ne.operando1 = ae1;
                                ne.operando2 = ae2;
                                RESULT = ne;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // var ::= ID LSQUAREB expression RSQUAREB 
            {
              NodeTree RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "var ::= ID LSQUAREB expression RSQUAREB \n"+this.parser.cadenaProduccion;
                                NodeVar nv = new NodeVar();
                                nv.identificador = id;
                                nv.nodeTree = e;
                                RESULT = nv;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // var ::= ID 
            {
              NodeTree RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "var ::= ID \n"+this.parser.cadenaProduccion;
                                NodeVar nv = new NodeVar();
                                nv.identificador = id;
                                RESULT = nv;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expression ::= simple_expression 
            {
              NodeTree RESULT =null;
		int seleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int seright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree se = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "expression ::= simple_expression \n"+this.parser.cadenaProduccion;
                                RESULT = se;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expression ::= var ASSIGN expression 
            {
              NodeTree RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree v = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "expression ::= var ASSIGN expression \n"+this.parser.cadenaProduccion;
                                NodeExpression ne = new NodeExpression();
                                ne.operador = sym.ASSIGN;
                                ne.operando1 = v;
                                ne.operando2 = e;
                                RESULT = ne;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // return_stmt ::= RETURN expression SEMICOLON 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "return_stmt ::= RETURN expression SEMICOLON \n"+this.parser.cadenaProduccion;
                                NodeStatement ns = new NodeStatement();
                                ns.nodo1 = e;
                                ns.tipoProduccion = "RETURN";
                                RESULT = ns;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // return_stmt ::= RETURN SEMICOLON 
            {
              NodeTree RESULT =null;
		
                                this.parser.cadenaProduccion = "return_stmt ::= RETURN SEMICOLON \n"+this.parser.cadenaProduccion;
                                NodeStatement ns = new NodeStatement();
                                ns.tipoProduccion = "RETURN";
                                RESULT = ns;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // for_stmt ::= FOR LCIRCLEB expression COMMA expression COMMA expression RCIRCLEB statement 
            {
              NodeTree RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		NodeTree e1 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		NodeTree e2 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree e3 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree s = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "for_stmt ::= FOR LCIRCLEB expression SEMICOLON expression SEMICOLON expression RCIRCLEB statement \n"+this.parser.cadenaProduccion;
                                NodeStatement fs = new NodeStatement();
                                fs.tipoProduccion = "FOR";
                                fs.nodo1 = e1;
                                fs.nodo2 = e2;
                                fs.nodo3 = e3;
                                fs.nodo4 = s;
                                RESULT = fs;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // while_stmt ::= WHILE LCIRCLEB expression RCIRCLEB statement 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree s = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "while_stmt ::= WHILE LCIRCLEB expression RCIRCLEB statement \n"+this.parser.cadenaProduccion;
                                NodeStatement ws = new NodeStatement();
                                ws.tipoProduccion = "WHILE";
                                ws.nodo1 = e;
                                ws.nodo2 = s;
                                RESULT = ws;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // iteration_stmt ::= for_stmt 
            {
              NodeTree RESULT =null;
		int fsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree fs = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "iteration_stmt ::= for_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = fs;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // iteration_stmt ::= while_stmt 
            {
              NodeTree RESULT =null;
		int wsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int wsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree ws = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "iteration_stmt ::= while_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = ws;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // selection_stmt ::= IF LCIRCLEB expression RCIRCLEB statement ELSE statement 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree s1 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree s2 = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "selection_stmt ::= IF LCIRCLEB expression RCIRCLEB statement ELSE statement \n"+this.parser.cadenaProduccion;
                                NodeStatement ns = new NodeStatement();
                                ns.tipoProduccion = "IF-ELSE";
                                ns.nodo1 = e;
                                ns.nodo2 = s1;
                                ns.nodo3 = s2;
                                RESULT = ns;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // selection_stmt ::= IF LCIRCLEB expression RCIRCLEB statement 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree s = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "selection_stmt ::= IF LCURLYB expression RCURLYB statement \n"+this.parser.cadenaProduccion;
                                NodeStatement ns = new NodeStatement();
                                ns.tipoProduccion = "IF";
                                ns.nodo1 = e;
                                ns.nodo2 = s;
                                RESULT = ns;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression_stmt ::= SEMICOLON 
            {
              NodeTree RESULT =null;
		
                                this.parser.cadenaProduccion = "expression_stmt ::= SEMICOLON \n"+this.parser.cadenaProduccion;
                                RESULT = null;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression_stmt ::= expression SEMICOLON 
            {
              NodeTree RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeTree e = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "expression_stmt ::= expression SEMICOLON \n"+this.parser.cadenaProduccion;
                                RESULT = e;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= return_stmt 
            {
              NodeTree RESULT =null;
		int rsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree rs = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement ::= return_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = rs;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= iteration_stmt 
            {
              NodeTree RESULT =null;
		int isleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int isright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree is = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement ::= iteration_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = is;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= selection_stmt 
            {
              NodeTree RESULT =null;
		int ssleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree ss = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement ::= selection_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = ss;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= compound_stmt 
            {
              NodeTree RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int csright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree cs = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement ::= compound_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = cs;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= expression_stmt 
            {
              NodeTree RESULT =null;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree es = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement ::= expression_stmt \n"+this.parser.cadenaProduccion;
                                RESULT = es;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement_list ::= 
            {
              ArrayList<NodeTree> RESULT =null;
		
                                this.parser.cadenaProduccion = "statement_list ::= EMPTY \n"+this.parser.cadenaProduccion;
                                ArrayList<NodeTree> nodeList = new ArrayList<NodeTree>();
                                RESULT = nodeList;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement_list ::= statement_list statement 
            {
              ArrayList<NodeTree> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<NodeTree> sl = (ArrayList<NodeTree>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree s = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "statement_list ::= statement_list statement \n"+this.parser.cadenaProduccion;
                                if(s != null){
                                    sl.add(s);
                                }
                                RESULT = sl;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // local_declarations ::= 
            {
              ArrayList<NodeTree> RESULT =null;
		
                                this.parser.cadenaProduccion = "local_declarations ::= EMPTY \n"+this.parser.cadenaProduccion;
                                ArrayList<NodeTree> nodeList = new ArrayList<NodeTree>();
                                RESULT = nodeList;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_declarations",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // local_declarations ::= local_declarations var_declaration 
            {
              ArrayList<NodeTree> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<NodeTree> ld = (ArrayList<NodeTree>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int vdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeVarDeclaration vd = (NodeVarDeclaration)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "local_declarations ::= local_declarations var_declaration \n"+this.parser.cadenaProduccion;
                                if(vd != null){
                                    ld.add(vd);
                                }
                                RESULT = ld;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_declarations",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // compound_stmt ::= LCURLYB local_declarations statement_list RCURLYB 
            {
              NodeTree RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<NodeTree> ld = (ArrayList<NodeTree>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<NodeTree> sl = (ArrayList<NodeTree>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "compound_stmt ::= LCURLYB local_declarations statement_list RCURLYB \n"+this.parser.cadenaProduccion;
                                NodeCompoundStmt ncs = new NodeCompoundStmt();
                                ncs.listaLocalDecl= ld;
                                ncs.listaStmtList = sl;
                                RESULT = ncs;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("compound_stmt",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param ::= type_specifier ID LSQUAREB RSQUAREB 
            {
              NodeTree RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Integer ts = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
                                this.parser.cadenaProduccion = "param ::= type_specifier ID LSQUAREB RSQUAREB \n"+this.parser.cadenaProduccion;
                                NodeParam np = new NodeParam();
                                np.typeSpecifier = ts;
                                np.identificador = id;
                                np.parametroVector = true;
                                RESULT = np;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param ::= type_specifier ID 
            {
              NodeTree RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer ts = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "param ::= type_specifier ID \n"+this.parser.cadenaProduccion;
                                NodeParam np = new NodeParam();
                                np.typeSpecifier = ts;
                                np.identificador = id;
                                np.parametroVector = false;
                                RESULT = np;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param_list ::= param 
            {
              NodeTree RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree p = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "param_list ::= param \n"+this.parser.cadenaProduccion;
                                NodeFunDeclaration nfd = new NodeFunDeclaration();
                                nfd.listaParam.add(p);
                                RESULT = nfd;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= param_list COMMA param 
            {
              NodeTree RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree pl = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree p = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "param_list ::= param_list COMMA param \n"+this.parser.cadenaProduccion;
                                if(p != null){
                                    ((NodeFunDeclaration) pl).listaParam.add(p);
                                }else{
                                    pl = new NodeFunDeclaration();
                                }
                                RESULT = pl;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // params ::= VOID 
            {
              NodeTree RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "params ::= VOID \n"+this.parser.cadenaProduccion;
                                NodeParam np = new NodeParam();
                                np.typeSpecifier = sym.VOID;
                                RESULT = np;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= param_list 
            {
              NodeTree RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree pl = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "params ::= param_list \n"+this.parser.cadenaProduccion;
                                RESULT = pl;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // fun_declaration ::= type_specifier ID LCIRCLEB params RCIRCLEB compound_stmt 
            {
              NodeFunDeclaration RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer ts = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int psleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int psright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodeTree ps = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int csright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree cs = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "fun_declaration ::= type_specifier ID LCIRCLEB params RCIRCLEB compound_stmt \n"+this.parser.cadenaProduccion;
                                if(ps instanceof NodeParam){
                                    NodeFunDeclaration nfd = new NodeFunDeclaration();
                                    nfd.typeSpecifier = ts;
                                    nfd.identificador = id;
                                    if(cs != null){
                                        nfd.nodoCompStmt = (NodeCompoundStmt)cs;
                                    }
                                    nfd.listaParam.add((NodeParam)ps);
                                    nfd.cantidadParametros = nfd.listaParam.size();
                                    RESULT = nfd;
                                }else{
                                    NodeFunDeclaration nfd = new NodeFunDeclaration();
                                    nfd.identificador = id;
                                    nfd.typeSpecifier = ts;
                                    if(cs != null){
                                        nfd.nodoCompStmt = (NodeCompoundStmt)cs;
                                    }
                                    nfd.listaParam = ((NodeFunDeclaration)ps).listaParam;
                                    nfd.cantidadParametros = nfd.listaParam.size();
                                    RESULT = nfd;
                                }
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fun_declaration",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_specifier ::= VOID 
            {
              Integer RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "type_specifier ::= VOID \n"+this.parser.cadenaProduccion;
                                RESULT = sym.VOID;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_specifier",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_specifier ::= INT 
            {
              Integer RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "type_specifier ::= INT \n"+this.parser.cadenaProduccion;
                                RESULT = sym.INT;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_specifier",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_declaration ::= type_specifier ID LSQUAREB NUM RSQUAREB SEMICOLON 
            {
              NodeVarDeclaration RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer ts = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
                                this.parser.cadenaProduccion = "var_declaration ::= type_specifier ID LSQUAREB NUM RSQUAREB SEMICOLON \n"+this.parser.cadenaProduccion;
                                NodeVarDeclaration nvd = new NodeVarDeclaration();
                                nvd.arreglo = true;
                                nvd.typeSpecifier = ts;
                                nvd.identificador = id;
                                nvd.tamanoArreglo = num;
                                RESULT = nvd;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_declaration",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= type_specifier ID SEMICOLON 
            {
              NodeVarDeclaration RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Integer ts = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                                this.parser.cadenaProduccion = "var_declaration ::= type_specifier ID SEMICOLON \n"+this.parser.cadenaProduccion;
                                NodeVarDeclaration nvd = new NodeVarDeclaration();
                                nvd.arreglo = false;
                                nvd.typeSpecifier = ts;
                                nvd.identificador = id;
                                RESULT = nvd;                                
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_declaration",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaration ::= fun_declaration 
            {
              NodeTree RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeFunDeclaration fd = (NodeFunDeclaration)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "declaration ::= fun_declaration \n"+this.parser.cadenaProduccion;
                                RESULT = fd;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaration ::= var_declaration 
            {
              NodeTree RESULT =null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeVarDeclaration vd = (NodeVarDeclaration)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "declaration ::= var_declaration \n"+this.parser.cadenaProduccion;
                                RESULT = vd;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaration_list ::= declaration 
            {
              NodeProgram RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree d = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "declaration_list ::= declaration \n"+this.parser.cadenaProduccion;
                                NodeProgram nodos = new NodeProgram();
                                nodos.listaDeclarationList.add(d);
                                RESULT = nodos;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaration_list ::= declaration_list declaration 
            {
              NodeProgram RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeProgram dl = (NodeProgram)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeTree d = (NodeTree)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "declaration_list ::= declaration_list declaration \n"+this.parser.cadenaProduccion;
                                if(d != null){
                                    dl.listaDeclarationList.add(d);
                                }
                                RESULT = dl;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= declaration_list 
            {
              NodeProgram RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodeProgram dl = (NodeProgram)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                this.parser.cadenaProduccion = "program ::= declaration_list \n"+this.parser.cadenaProduccion;
                                System.out.println(this.parser.cadenaProduccion);
                                this.parser.root = dl;
                                RESULT = dl;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodeProgram start_val = (NodeProgram)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

