
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 21 17:06:07 CLT 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 13;
  public static final int LT = 10;
  public static final int ELSE = 24;
  public static final int SEMICOLON = 21;
  public static final int RCIRCLEB = 20;
  public static final int INT = 25;
  public static final int WHILE = 27;
  public static final int LCURLYB = 15;
  public static final int SUMA = 5;
  public static final int RETURN = 26;
  public static final int IF = 23;
  public static final int GT = 12;
  public static final int ID = 30;
  public static final int NUM = 31;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int LCIRCLEB = 19;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int EXPO2 = 4;
  public static final int ASSIGN = 2;
  public static final int EQ = 9;
  public static final int EXPO1 = 3;
  public static final int LEQ = 11;
  public static final int RCURLYB = 16;
  public static final int FOR = 28;
  public static final int VOID = 29;
  public static final int NEQ = 14;
  public static final int LSQUAREB = 17;
  public static final int RSQUAREB = 18;
  public static final int RESTA = 7;
}

